name: pg
channels:
  - conda-forge
  - gimli
dependencies:
   - pygimli=1.3.1
   - ipykernel
   - pip
   - pip:
     - "--editable=git+https://gitlab.com/resistivity-net/bert.git#egg=pybert&subdirectory=python"